import { ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, inject, signal, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { LanguageService } from '../../core/services/language.service';
import { MockDatabaseService } from '../../data/mock/mock-database.service';
import { PostStatus, UserRow } from '../../data/mock/mock-schema.model';

interface ProfilePost {id:number;title:string;content:string;thumbnail:string;date:string;likes:number;comments:number;status:PostStatus;}

@Component({selector:'app-profile',standalone:true,imports:[RouterLink],templateUrl:'./profile.component.html',styleUrl:'./profile.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,encapsulation:ViewEncapsulation.None,schemas:[CUSTOM_ELEMENTS_SCHEMA]})
export class ProfileComponent {
  private readonly route=inject(ActivatedRoute);private readonly database=inject(MockDatabaseService);protected readonly auth=inject(AuthService);protected readonly language=inject(LanguageService);private readonly revision=signal(0);
  protected readonly tab=signal<'home'|'about'>('home');protected readonly page=signal(1);protected readonly pageSize=5;
  private readonly requestedId=Number(this.route.snapshot.paramMap.get('id'))||this.auth.currentUser()?.id||1;
  protected readonly user=computed<UserRow|null>(()=>{this.revision();return this.database.table('users').find(row=>row.id===this.requestedId)??null;});
  protected readonly ownProfile=computed(()=>this.auth.currentUser()?.id===this.user()?.id);
  protected readonly posts=computed<ProfilePost[]>(()=>{this.revision();const user=this.user();if(!user)return[];const langId=this.language.locale()==='vi'?2:1;const translations=this.database.table('post_translations');const likes=this.database.table('post_likes');const comments=this.database.table('comments');return this.database.table('posts').filter(p=>p.author_id===user.id&&!p.deleted_at&&(this.ownProfile()||p.status==='PUBLISHED')).map(p=>({id:p.id,title:translations.find(t=>t.post_id===p.id&&t.language_id===langId)?.title??translations.find(t=>t.post_id===p.id)?.title??'Untitled',content:translations.find(t=>t.post_id===p.id&&t.language_id===langId)?.content??translations.find(t=>t.post_id===p.id)?.content??'',thumbnail:p.thumbnail,date:p.created_at,likes:likes.filter(x=>x.post_id===p.id&&x.is_liked).length,comments:comments.filter(x=>x.post_id===p.id&&!x.deleted_at).length,status:p.status})).sort((a,b)=>+new Date(b.date)-+new Date(a.date));});
  protected readonly totalLikes=computed(()=>this.posts().reduce((sum,p)=>sum+p.likes,0));protected readonly featured=computed(()=>[...this.posts()].sort((a,b)=>b.likes-a.likes)[0]??null);protected readonly totalPages=computed(()=>Math.max(1,Math.ceil(this.posts().length/this.pageSize)));protected readonly pages=computed(()=>Array.from({length:this.totalPages()},(_,i)=>i+1));protected readonly visiblePosts=computed(()=>this.posts().slice((this.page()-1)*this.pageSize,this.page()*this.pageSize));
  protected name():string{const user=this.user();return user?.full_name||user?.user_name||'Anonymous';}protected avatar():string{return this.user()?.avatar||`https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(this.name())}`;}protected excerpt(html:string):string{const text=html.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();return text.length>120?text.slice(0,120)+'...':text;}protected formatDate(value:string,joined=false):string{return new Intl.DateTimeFormat(this.language.locale()==='vi'?'vi-VN':'en-US',joined?{month:'2-digit',year:'numeric'}:{month:'short',day:'numeric'}).format(new Date(value));}
  protected statusLabel(status:PostStatus):string{const vi={DRAFT:'Bản nháp',PENDING:'Chờ duyệt',PUBLISHED:'Đã xuất bản',REJECTED:'Bị từ chối'};const en={DRAFT:'Draft',PENDING:'Pending',PUBLISHED:'Published',REJECTED:'Rejected'};return(this.language.locale()==='vi'?vi:en)[status];}
  protected roleLabel():string{const role=this.user()?.role_id;return role===1?'Super Admin':role===2?'Blogger':this.language.locale()==='vi'?'Thành viên':'Member';}
  protected upload(event:Event,field:'avatar'|'cover_image'):void{if(!this.ownProfile())return;const file=(event.target as HTMLInputElement).files?.[0];if(!file||!file.type.startsWith('image/')||file.size>5*1024*1024)return;const reader=new FileReader();reader.onload=()=>{const users=this.database.table('users');const target=users.find(row=>row.id===this.requestedId);if(target){target[field]=String(reader.result);target.updated_at=new Date().toISOString();this.database.write('users',users);this.revision.update(x=>x+1);this.auth.refreshProfile().subscribe();}};reader.readAsDataURL(file);}
}
