import { AfterViewInit, ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, ElementRef, inject, signal, ViewChild, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { LanguageService } from '../../core/services/language.service';
import { MockDatabaseService } from '../../data/mock/mock-database.service';
declare const Quill:any;

@Component({selector:'app-post-form',standalone:true,imports:[RouterLink],templateUrl:'./post-form.component.html',styleUrl:'./post-form.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,encapsulation:ViewEncapsulation.None,schemas:[CUSTOM_ELEMENTS_SCHEMA]})
export class PostFormComponent implements AfterViewInit{
  private readonly database=inject(MockDatabaseService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);protected readonly auth=inject(AuthService);protected readonly language=inject(LanguageService);
  @ViewChild('editor') editorRef!:ElementRef<HTMLElement>; private editor:any;
  protected readonly editId=signal<number|null>(null);protected readonly title=signal('');protected readonly content=signal('');protected readonly thumbnail=signal('');protected readonly sourceLanguageId=signal(2);protected readonly categoryId=signal(1);protected readonly previewOpen=signal(false);protected readonly previewLanguageId=signal(2);protected readonly translateTargets=signal<number[]>([]);protected readonly error=signal('');protected readonly translatedPreview=signal<{title:string;content:string}|null>(null);protected readonly translating=signal(false);private readonly translators=new Map<string,any>();
  protected readonly languages=computed(()=>this.database.table('languages').filter(row=>!row.deleted_at));
  protected readonly categories=computed(()=>{const rows=this.database.table('categories').filter(row=>!row.deleted_at);const trans=this.database.table('category_translation');return rows.map(row=>({id:row.id,name:trans.find(t=>t.category_id===row.id&&t.language_id===this.sourceLanguageId())?.name??trans.find(t=>t.category_id===row.id)?.name??`#${row.id}`}));});
  protected readonly previewTitle=computed(()=>this.previewLanguageId()===this.sourceLanguageId()?this.title():(this.translatedPreview()?.title??this.title()));
  protected readonly previewLanguageName=computed(()=>this.languages().find(item=>item.id===this.previewLanguageId())?.name??'');
  protected readonly previewContent=computed(()=>this.previewLanguageId()===this.sourceLanguageId()?this.content():(this.translatedPreview()?.content??this.content()));
  ngAfterViewInit():void{this.editor=new Quill(this.editorRef.nativeElement,{theme:'snow',placeholder:'Viết nội dung ở đây...',modules:{toolbar:[[{header:[2,3,false]}],['bold','italic','underline','strike'],['blockquote','code-block'],[{list:'ordered'},{list:'bullet'}],['link','image'],['clean']]}});this.editor.on('text-change',()=>this.content.set(this.editor.root.innerHTML));const raw=this.route.snapshot.paramMap.get('id');if(raw)this.loadPost(Number(raw));}
  private loadPost(id:number):void{const post=this.database.table('posts').find(row=>row.id===id&&row.author_id===this.auth.currentUser()?.id);if(!post)return;const trans=this.database.table('post_translations').find(row=>row.post_id===id&&row.language_id===(post.source_language_id??2));this.editId.set(id);this.sourceLanguageId.set(post.source_language_id??2);this.previewLanguageId.set(post.source_language_id??2);this.categoryId.set(post.category_id);this.thumbnail.set(post.thumbnail);this.title.set(trans?.title??'');this.content.set(trans?.content??'');this.editor.root.innerHTML=trans?.content??'';this.translateTargets.set(this.database.table('post_translations').filter(row=>row.post_id===id&&row.language_id!==post.source_language_id).map(row=>row.language_id));}
  protected handleThumbnail(event:Event):void{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>5*1024*1024){this.error.set('Ảnh không được vượt quá 5 MB.');return;}const reader=new FileReader();reader.onload=()=>this.thumbnail.set(String(reader.result??''));reader.readAsDataURL(file);}
  protected toggleTranslation(id:number,checked:boolean):void{this.translateTargets.update(rows=>checked?[...new Set([...rows,id])]:rows.filter(row=>row!==id));}
  protected changeSourceLanguage(id:number):void{this.sourceLanguageId.set(id);this.previewLanguageId.set(id);this.translateTargets.update(rows=>rows.filter(row=>row!==id));this.translatedPreview.set(null);this.error.set('');}
  protected async setPreviewLanguage(id:number):Promise<void>{this.previewLanguageId.set(id);this.translatedPreview.set(null);if(id===this.sourceLanguageId())return;this.translating.set(true);try{this.translatedPreview.set(await this.translateDraft(this.title(),this.content(),id));}catch{this.error.set(this.language.locale()==='vi'?'Trình duyệt này chưa hỗ trợ mô hình dịch trực tiếp trên thiết bị.':'On-device translation is not available in this browser yet.');}finally{this.translating.set(false);}}
  private async translateDraft(title:string,html:string,targetId:number):Promise<{title:string;content:string}>{const source=this.languages().find(l=>l.id===this.sourceLanguageId())?.code;const target=this.languages().find(l=>l.id===targetId)?.code;const api=(window as any).Translator;if(!source||!target||!api?.create)throw new Error('TRANSLATOR_UNAVAILABLE');const key=`${source}:${target}`;let translator=this.translators.get(key);if(!translator){translator=await api.create({sourceLanguage:source,targetLanguage:target});this.translators.set(key,translator);}const container=document.createElement('div');container.innerHTML=html;const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];while(walker.nextNode())if(walker.currentNode.nodeValue?.trim())nodes.push(walker.currentNode as Text);await Promise.all(nodes.map(async node=>node.nodeValue=await translator.translate(node.nodeValue!.trim())));return{title:await translator.translate(title),content:container.innerHTML};}
  protected async save(status:'DRAFT'|'PENDING'):Promise<void>{const title=this.title().trim();const content=this.content();if(!title||!content.replace(/<[^>]*>/g,'').trim()||!this.thumbnail()){this.error.set(this.language.locale()==='vi'?'Vui lòng nhập tiêu đề, nội dung và chọn ảnh đại diện!':'Please enter a title, content and post thumbnail.');return;}const translated=[];try{for(const languageId of this.translateTargets())if(languageId!==this.sourceLanguageId())translated.push({languageId,...await this.translateDraft(title,content,languageId)});}catch{this.error.set(this.language.locale()==='vi'?'Không thể hoàn tất bản dịch nên bài viết chưa được lưu.':'Translation could not be completed, so the post was not saved.');return;}const now=new Date().toISOString();const posts=this.database.table('posts');const id=this.editId()??this.database.nextId('posts');const existing=posts.find(row=>row.id===id);if(existing){existing.category_id=this.categoryId();existing.source_language_id=this.sourceLanguageId();existing.thumbnail=this.thumbnail();existing.status=status;existing.submitted_at=status==='PENDING'?now:null;existing.updated_at=now;}else posts.push({id,author_id:this.auth.currentUser()!.id,category_id:this.categoryId(),source_language_id:this.sourceLanguageId(),thumbnail:this.thumbnail(),status,rejection_reason:null,submitted_at:status==='PENDING'?now:null,reviewed_by:null,reviewed_at:null,published_at:null,created_at:now,updated_at:now,deleted_at:null});this.database.write('posts',posts);const translations=this.database.table('post_translations').filter(row=>row.post_id!==id);translations.push({id:this.database.nextId('post_translations'),post_id:id,language_id:this.sourceLanguageId(),title,content,is_auto_translated:false,created_at:now,updated_at:now});let nextId=Math.max(0,...translations.map(row=>row.id))+1;for(const row of translated)translations.push({id:nextId++,post_id:id,language_id:row.languageId,title:row.title,content:row.content,is_auto_translated:true,created_at:now,updated_at:now});this.database.write('post_translations',translations);void this.router.navigate(['/owner/posts']);}
}
