import { ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, inject, signal, ViewEncapsulation } from '@angular/core';
import { LanguageService } from '../../core/services/language.service';import { AuthService } from '../../core/services/auth.service';import { MockDatabaseService } from '../../data/mock/mock-database.service';import { UserRow } from '../../data/mock/mock-schema.model';
@Component({selector:'app-admin-users',standalone:true,templateUrl:'./admin-users.component.html',styleUrl:'./admin-users.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,encapsulation:ViewEncapsulation.None,schemas:[CUSTOM_ELEMENTS_SCHEMA]})
export class AdminUsersComponent{
 private readonly db=inject(MockDatabaseService);protected readonly language=inject(LanguageService);private readonly auth=inject(AuthService);private readonly rev=signal(0);protected readonly search=signal('');protected readonly role=signal(0);protected readonly active=signal('');protected readonly page=signal(1);protected readonly pageSize=signal(5);protected readonly addOpen=signal(false);protected readonly confirmUser=signal<UserRow|null>(null);protected readonly confirmKind=signal<'status'|'role'|null>(null);protected readonly pendingRole=signal(2);protected readonly showPassword=signal(false);protected readonly error=signal('');protected readonly fullName=signal('');protected readonly userName=signal('');protected readonly email=signal('');protected readonly password=signal('');protected readonly confirmPassword=signal('');protected readonly newRole=signal(2);
 protected readonly users=computed(()=>{this.rev();const q=this.search().trim().toLowerCase();return this.db.table('users').filter(u=>(!q||[u.full_name,u.user_name,u.email].some(x=>(x??'').toLowerCase().includes(q)))&&(!this.role()||u.role_id===this.role())&&(!this.active()||(this.active()==='active'?u.is_active:!u.is_active)));});protected readonly pages=computed(()=>Array.from({length:Math.max(1,Math.ceil(this.users().length/this.pageSize()))},(_,i)=>i+1));protected readonly visible=computed(()=>this.users().slice((this.page()-1)*this.pageSize(),this.page()*this.pageSize()));protected initials(u:UserRow):string{return(u.full_name||u.user_name).split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();}protected roleName(id:number):string{return id===1?'Super Admin':id===2?'Blog Owner':'Authenticated User';}protected date(v:string):string{return new Intl.DateTimeFormat(this.language.locale()==='vi'?'vi-VN':'en-US').format(new Date(v));}protected filter():void{this.page.set(1);}protected askStatus(u:UserRow):void{if(u.role_id===1)return;this.confirmUser.set(u);this.confirmKind.set('status');}protected askRole(u:UserRow,role:number):void{if(u.role_id===1)return;this.confirmUser.set(u);this.pendingRole.set(role);this.confirmKind.set('role');}
 protected applyConfirm():void{const chosen=this.confirmUser();if(!chosen)return;const users=this.db.table('users');const user=users.find(u=>u.id===chosen.id);if(!user)return;const before=structuredClone(user);let action='';if(this.confirmKind()==='status'){user.is_active=!user.is_active;action=user.is_active?'USER_UNLOCKED':'USER_LOCKED';}else{user.role_id=this.pendingRole();action='USER_ROLE_CHANGED';}user.updated_at=new Date().toISOString();this.db.write('users',users);this.log(action,user,before);this.confirmKind.set(null);this.confirmUser.set(null);this.rev.update(x=>x+1);}
 protected addUser():void{const name=this.fullName().trim(),username=this.userName().trim(),email=this.email().trim().toLowerCase();if(!name||!username||!email||this.password().length<6||this.password()!==this.confirmPassword()){this.error.set(this.language.locale()==='vi'?'Vui lòng nhập đủ thông tin; mật khẩu tối thiểu 6 ký tự và phải trùng nhau.':'Complete all fields; passwords must match and contain at least 6 characters.');return;}const users=this.db.table('users');if(users.some(u=>u.email.toLowerCase()===email||u.user_name.toLowerCase()===username.toLowerCase())){this.error.set(this.language.locale()==='vi'?'Email hoặc tên đăng nhập đã tồn tại.':'Email or username already exists.');return;}const now=new Date().toISOString();const user:UserRow={id:this.db.nextId('users'),user_name:username,email,full_name:name,phone:null,avatar:null,cover_image:null,date_of_birth:null,is_active:true,password_hash:'MOCK_PASSWORD_HASH',email_verified:true,role_id:this.newRole(),otp_code:null,otp_created_at:null,otp_ttl_seconds:180,created_at:now,updated_at:now};users.push(user);this.db.write('users',users);this.db.setRegisteredPassword(email,this.password());this.log('USER_CREATED',user,null);this.closeAdd();this.rev.update(x=>x+1);}
 protected closeAdd():void{this.addOpen.set(false);this.fullName.set('');this.userName.set('');this.email.set('');this.password.set('');this.confirmPassword.set('');this.error.set('');}private log(action:string,user:UserRow,before:UserRow|null):void{const actor=this.auth.currentUser();const logs=this.db.table('audit_logs');logs.push({id:this.db.nextId('audit_logs'),actor_id:actor?.id??null,actor_name:actor?.fullName??null,actor_role:actor?.role.nameRole??null,action,entity_type:'USER',entity_id:user.id,entity_label:user.full_name||user.user_name,before_data:before,after_data:structuredClone(user),metadata:null,ip_address:null,user_agent:navigator.userAgent,created_at:new Date().toISOString()});this.db.write('audit_logs',logs);}
}
