import { ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, DestroyRef, effect, inject, Injector, signal, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ContentCategory, ContentTranslation } from '../../core/models/content.model';
import { AdminContentApiService, CategoryTranslationPayload } from '../../core/services/admin-content-api.service';
import { LanguageService, SystemLanguage } from '../../core/services/language.service';
import { NotificationService } from '../../core/services/notification.service';
import { buildPaginationItems } from '../../shared/utils/pagination';
import { bindQueryState, positiveInteger } from '../../shared/utils/query-state';

interface CategoryView {category:ContentCategory;translation?:ContentTranslation;posts:number;}
interface CategoryFormCopy{nameLabel:string;namePlaceholder:string;descriptionLabel:string;descriptionPlaceholder:string;}
const CATEGORY_FORM_COPY:Record<string,CategoryFormCopy>={
  vi:{nameLabel:'Tên danh mục',namePlaceholder:'VD: Công nghệ',descriptionLabel:'Mô tả',descriptionPlaceholder:'Mô tả ngắn...'},
  en:{nameLabel:'Category name',namePlaceholder:'e.g. Technology',descriptionLabel:'Description',descriptionPlaceholder:'Short description...'},
  zh:{nameLabel:'分类名称',namePlaceholder:'例如：科技',descriptionLabel:'描述',descriptionPlaceholder:'简短描述...'},
};
const CATEGORY_NAMES:Record<string,Record<string,string>>={
  vi:{technology:'Công nghệ',lifestyle:'Đời sống',sports:'Thể thao',programming:'Lập trình','ux design':'Thiết kế UX',society:'Xã hội',news:'Tin tức',economics:'Kinh tế'},
  en:{'công nghệ':'Technology','đời sống':'Lifestyle','thể thao':'Sports','lập trình':'Programming','thiết kế ux':'UX Design','xã hội':'Society','tin tức':'News','kinh tế':'Economics'},
  zh:{'công nghệ':'科技','đời sống':'生活','thể thao':'体育','lập trình':'编程','thiết kế ux':'用户体验设计','xã hội':'社会','tin tức':'新闻','kinh tế':'经济',technology:'科技',lifestyle:'生活',sports:'体育',programming:'编程','ux design':'用户体验设计',society:'社会',news:'新闻',economics:'经济'},
};

@Component({selector:'app-admin-categories',standalone:true,templateUrl:'./admin-categories.component.html',styleUrl:'./admin-categories.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,encapsulation:ViewEncapsulation.None,schemas:[CUSTOM_ELEMENTS_SCHEMA]})
export class AdminCategoriesComponent {
  private readonly api=inject(AdminContentApiService);private readonly notifications=inject(NotificationService);protected readonly language=inject(LanguageService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly injector=inject(Injector);private readonly destroyRef=inject(DestroyRef);
  private readonly items=signal<ContentCategory[]>([]);private readonly total=signal(0);private readonly totalPageCount=signal(1);
  protected readonly search=signal('');protected readonly page=signal(1);protected readonly pageSize=signal(5);protected readonly pageInput=signal(1);protected readonly sizeInput=signal(5);protected readonly modal=signal<'add'|'edit'|null>(null);protected readonly deleteTarget=signal<CategoryView|null>(null);protected readonly editingId=signal<number|null>(null);protected readonly sourceLanguageId=signal(2);protected readonly name=signal('');protected readonly description=signal('');protected readonly retranslate=signal(false);protected readonly error=signal('');
  protected readonly languages:SystemLanguage[]=this.language.availableLanguages();
  private readonly translators=new Map<string,{translate(value:string):Promise<string>}>();
  constructor(){bindQueryState(this.route,this.router,this.injector,this.destroyRef,{q:{signal:this.search,defaultValue:''},page:{signal:this.page,defaultValue:1,parse:positiveInteger(1)},limit:{signal:this.pageSize,defaultValue:5,parse:positiveInteger(5,100)}});this.pageInput.set(this.page());this.sizeInput.set(this.pageSize());effect(()=>{const page=this.page(),limit=this.pageSize(),search=this.search().trim(),language=this.language.locale();this.api.categories({page,limit,search,language,sort:'name-asc'}).subscribe({next:r=>{this.items.set(r.data.items);this.total.set(r.data.pagination.total);this.totalPageCount.set(Math.max(1,r.data.pagination.totalPages));},error:e=>{this.items.set([]);this.error.set(e instanceof Error?e.message:'LOAD_CATEGORIES_FAILED');}});},{allowSignalWrites:true});}
  protected readonly rows=computed<CategoryView[]>(()=>this.items().map(category=>({category,translation:category.translations.find(item=>item.languageId===this.language.languageId())??category.translations[0],posts:Number(category.postsCount??0)})));
  protected readonly totalPages=computed(()=>this.totalPageCount());protected readonly pages=computed(()=>buildPaginationItems(this.page(),this.totalPages()));protected readonly visibleRows=computed(()=>this.rows());protected readonly summary=computed(()=>{const total=this.total();const from=total?(this.page()-1)*this.pageSize()+1:0;const to=Math.min(this.page()*this.pageSize(),total);return this.language.translate('pagination.summary',{from,to,total});});
  protected readonly sourceLanguage=computed(()=>this.languages.find(item=>item.id===this.sourceLanguageId())??this.languages[0]);protected readonly formCopy=computed(()=>CATEGORY_FORM_COPY[this.sourceLanguage()?.code.toLowerCase()]??CATEGORY_FORM_COPY['en']);
  protected filter(value:string):void{this.search.set(value);this.page.set(1);}protected changePage(value:number):void{const next=Math.min(Math.max(1,value),this.totalPages());this.page.set(next);this.pageInput.set(next);}protected applyPage():void{this.changePage(this.pageInput());}protected applyPageSize():void{const size=Math.min(100,Math.max(1,Math.trunc(this.sizeInput()||1)));this.pageSize.set(size);this.sizeInput.set(size);this.changePage(1);}
  protected openAdd():void{const current=this.languages.find(item=>item.code.toLowerCase()===this.language.locale().toLowerCase());this.editingId.set(null);this.sourceLanguageId.set(current?.id??this.language.languageId());this.name.set('');this.description.set('');this.error.set('');this.modal.set('add');requestAnimationFrame(()=>this.synchronizeSourceLanguageSelect());}
  protected openEdit(row:CategoryView):void{const sourceId=this.language.languageId();const translation=row.category.translations.find(item=>item.languageId===sourceId)??row.translation;this.editingId.set(row.category.id);this.sourceLanguageId.set(sourceId);this.name.set(translation?.name??'');this.description.set(translation?.des??'');this.error.set('');this.modal.set('edit');}
  protected changeLanguage(id:number):void{this.sourceLanguageId.set(id);if(this.modal()!=='edit')return;const row=this.items().find(item=>item.id===this.editingId());const translation=row?.translations.find(item=>item.languageId===id);this.name.set(translation?.name??'');this.description.set(translation?.des??'');}
  protected async save():Promise<void>{const name=this.name().trim();const source=this.sourceLanguage();if(!name||!source){this.error.set(this.language.choose('Vui lòng nhập tên danh mục.','Enter a category name.'));return;}this.error.set('');const isNew=this.modal()==='add';const payload={sourceLanguageId:source.id,translations:await this.buildTranslations(name,this.description().trim(),source)};const request=isNew?this.api.createCategory(payload):this.api.updateCategory(this.editingId()!,payload);request.subscribe({next:()=>{this.modal.set(null);this.error.set('');this.notifications.success(isNew?'Tạo danh mục thành công.':'Cập nhật danh mục thành công.',isNew?'Category created successfully.':'Category updated successfully.');this.reload();},error:e=>this.notifications.fromApi(e)});}
  protected remove():void{const target=this.deleteTarget();if(!target)return;this.api.deleteCategory(target.category.id).subscribe({next:()=>{this.deleteTarget.set(null);this.page.set(1);this.notifications.success('Xóa danh mục thành công.','Category deleted successfully.');this.reload();},error:e=>this.notifications.fromApi(e)});}
  private async buildTranslations(value:string,description:string,source:SystemLanguage):Promise<CategoryTranslationPayload[]>{const existing=this.items().find(item=>item.id===this.editingId());return Promise.all(this.languages.map(async target=>{if(target.id===source.id)return{languageId:target.id,name:value,des:description,isAutoTranslated:false};const current=existing?.translations.find(item=>item.languageId===target.id);const translatedName=this.translateName(value,target.code)??await this.translateValue(value,source.code,target.code).catch(()=>current?.name??value);const translatedDescription=description?await this.translateValue(description,source.code,target.code).catch(()=>current?.des??description):(current?.des??'');return{languageId:target.id,name:translatedName,des:translatedDescription,isAutoTranslated:true};}));}
  private translateName(value:string,target:string):string|undefined{return CATEGORY_NAMES[target.toLowerCase()]?.[value.toLowerCase()];}
  private async translateValue(value:string,source:string,target:string):Promise<string>{if(!value||source===target)return value;const factory=(window as unknown as {Translator?:{create(options:{sourceLanguage:string;targetLanguage:string}):Promise<{translate(value:string):Promise<string>}>}}).Translator;if(!factory?.create)throw new Error('TRANSLATOR_UNAVAILABLE');const key=`${source}:${target}`;let translator=this.translators.get(key);if(!translator){translator=await factory.create({sourceLanguage:source,targetLanguage:target});this.translators.set(key,translator);}return translator.translate(value);}
  private reload():void{this.api.categories({page:this.page(),limit:this.pageSize(),search:this.search().trim(),language:this.language.locale(),sort:'name-asc'}).subscribe(r=>{this.items.set(r.data.items);this.total.set(r.data.pagination.total);this.totalPageCount.set(Math.max(1,r.data.pagination.totalPages));});}
  private synchronizeSourceLanguageSelect():void{const select=document.querySelector<HTMLSelectElement>('.category-modal select');if(!select)return;select.value=String(this.sourceLanguageId());select.dispatchEvent(new Event('change',{bubbles:true}));}
}
