/*
 * Offline UI pack used while the backend translation provider is unavailable.
 * Keys are the English fallback strings already used by Angular templates.
 */
export const ZH_UI: Record<string, string> = {
  'Home':'首页','Profile':'个人资料','Admin Dashboard':'管理员控制面板','Dashboard':'控制面板',
  'System Dashboard':'系统控制面板','Admin workspace':'管理工作区','Manage Posts':'管理文章',
  'Manage posts':'管理文章','Manage Users':'管理用户','Manage Categories':'管理分类',
  'Manage Languages':'管理语言','Back home':'返回首页','Back to Blog':'返回博客',
  'Latest Posts':'最新文章','Staff Picks':'精选文章','Recommended topics':'推荐主题',
  'Recommended for you':'为你推荐','Keep reading':'继续阅读','View all':'查看全部',
  'Featured post':'精选文章','Article not found':'未找到文章','Responses':'回复',
  'Follow':'关注','Reply':'回复','Write a reply...':'写回复...','What are your thoughts?':'分享你的想法...',
  'You need to':'你需要','sign in':'登录','to leave a response.':'后才能发表评论。',
  'No articles found.':'未找到文章。','No posts yet.':'暂无文章。','User not found.':'未找到用户。',
  'This article does not exist, is not published, or you cannot preview it.':'该文章不存在、尚未发布，或你无权预览。',

  'Add User':'添加用户','Create user':'创建用户','User':'用户','USER':'用户',
  'Username':'用户名','Full name':'姓名','Password':'密码','Confirm password':'确认密码',
  'All roles':'所有角色','All statuses':'所有状态','Active':'正常','Locked':'已锁定',
  'Lock':'锁定','Unlock':'解锁','Lock account':'锁定账户','Unlock account':'解锁账户',
  'Change role':'更改角色','Role':'角色','ROLE':'角色','Status':'状态','STATUS':'状态',
  'Joined':'加入时间','JOINED':'加入时间','Apply this change to':'将此更改应用于',
  'No users found.':'未找到用户。','Email or username already exists.':'邮箱或用户名已存在。',
  'Complete all fields; passwords must match and contain at least 6 characters.':'请填写所有字段；两次密码必须一致且至少包含6个字符。',

  'Add Category':'添加分类','Edit Category':'编辑分类','Delete category':'删除分类',
  'Category':'分类','CATEGORY':'分类','Name (EN)':'名称（英文）','Name (VI)':'名称（越南语）',
  'NAME (EN)':'名称（英文）','NAME (VI)':'名称（越南语）','POSTS':'文章数',
  'Search categories...':'搜索分类...','No categories found.':'未找到分类。','Missing':'缺失',
  'Source language':'源语言','Language version being edited':'正在编辑的语言版本',
  'Enter once, translate automatically':'输入一次，自动翻译',
  'The system will create and save versions for every other language.':'系统将自动创建并保存其他语言版本。',
  'Retranslate other languages':'重新翻译其他语言',
  'Existing translations will be overwritten after confirmation.':'确认后将覆盖现有翻译。',
  'Create & translate':'创建并翻译','Enter a category name.':'请输入分类名称。',
  'Are you sure you want to delete':'确定要删除',

  'Add Language':'添加语言','Add language':'添加语言','Edit Language':'编辑语言',
  'Delete language':'删除语言','Language':'语言','LANGUAGE':'语言','Languages':'语言',
  'Language code':'语言代码','Language name':'语言名称','Code':'代码','CODE':'代码',
  'Flag':'国旗','FLAG':'国旗','Default':'默认','DEFAULT':'默认','Set as default':'设为默认',
  'Change default':'更改默认语言','Set as the system default language':'设为系统默认语言',
  'The default language cannot be deleted':'不能删除默认语言','No languages yet.':'暂无语言。',
  'This language code already exists.':'该语言代码已存在。',
  'Enter a name and a 2–5 letter language code.':'请输入名称和2至5个字母的语言代码。',
  'The flag is selected automatically from the language code.':'系统会根据语言代码自动选择国旗。',
  'The language list determines which languages blog owners can translate posts to, and the display language options for readers.':'语言列表决定博客作者可翻译的目标语言以及读者可选择的显示语言。',
  'Related translations will also be deleted. Delete':'相关翻译也将被删除。确定删除',
  'e.g. ja, fr, de':'例如：ja、fr、de',

  'New Post':'新建文章','New post':'新文章','Edit Post':'编辑文章','Post Preview':'文章预览',
  'Post Title':'文章标题','Post Content':'文章内容','Post Language':'文章语言',
  'Post thumbnail':'文章封面','Enter post title...':'输入文章标题...',
  'Choose a JPG, PNG or WebP image (max 5 MB)':'选择 JPG、PNG 或 WebP 图片（最大5 MB）',
  'Translate to other languages':'翻译为其他语言','Select the languages you want to translate automatically.':'选择需要自动翻译的语言。',
  'Save Draft':'保存草稿','Submit for review':'提交审核','Read Full Article':'阅读全文',
  'Search posts...':'搜索文章...','Newest first':'最新优先','Oldest first':'最早优先',
  'Title: A to Z':'标题：A 到 Z','Title: Z to A':'标题：Z 到 A','Title':'标题','TITLE':'标题',
  'Author':'作者','AUTHOR':'作者','Date':'日期','All':'全部','No posts found.':'未找到文章。',
  'Approve':'批准','Approve post':'批准文章','Approve and publish this post?':'批准并发布这篇文章？',
  'Reject post':'拒绝文章','Rejection reason':'拒绝原因',
  'Enter details so the author can revise the post...':'请输入详细原因，以便作者修改文章...',
  'Please enter a rejection reason.':'请输入拒绝原因。',
  'Please enter a title, content and post thumbnail.':'请输入标题、内容并选择文章封面。',
  'Translation could not be completed, so the post was not saved.':'翻译未完成，因此文章尚未保存。',
  'On-device translation is not available in this browser yet.':'此浏览器暂不支持设备端翻译。',
  'Translating…':'正在翻译…',

  'Content by category':'按分类统计内容','Recent activity':'最近活动',
  'Latest events across the system':'系统中的最新事件','Engagement trend':'互动趋势',
  'Likes and comments over time':'点赞和评论趋势','Post status':'文章状态',
  'Current content distribution':'当前内容分布','Top performing posts':'热门文章',
  'Ranked by likes and comments':'按点赞和评论排名','Translation coverage':'翻译覆盖率',
  'Vietnamese – English content availability':'越南语和英语内容可用情况',
  'Published posts by category':'各分类已发布文章数',
  'Monitor content, users and engagement performance across the system.':'监控系统中的内容、用户和互动表现。',
  'Likes':'点赞','likes':'点赞','Comments':'评论','Posts':'文章','posts':'文章',
  'Published':'已发布','Draft':'草稿','Pending':'待审核','Rejected':'已拒绝','Approved':'已批准',
  'Users':'用户','Pending Posts':'待审核文章','Categories':'分类',
  'Engagement / post':'每篇文章互动数',
  'Available in all languages':'所有语言均可用','Current language only':'仅当前语言',
  'Missing current language':'缺少当前语言版本','Auto-translated':'自动翻译',
  'Content availability across system languages':'系统各语言的内容可用情况',
  'Total Posts':'文章总数','Drafts':'草稿','Preview':'预览',
  'Category name':'分类名称','CATEGORY NAME':'分类名称',
  'Login succeeded':'登录成功','Logged out':'退出登录','Language created':'已创建语言',
  'Default language changed':'默认语言已更改','Post approved':'文章已批准',
  'Post rejected':'文章已拒绝','Category created':'已创建分类',
  'Category updated':'已更新分类','Category deleted':'已删除分类',
  'Activity Logs':'活动日志','System accountability':'系统审计',
  'Track administrative changes and important security events.':'跟踪管理变更和重要安全事件。',
  'Read only':'只读','Search actor or target...':'搜索执行者或对象...',
  'All actions':'所有操作','All entities':'所有对象','From':'开始日期','To':'结束日期','Reset':'重置',
  'Time':'时间','TIME':'时间','Actor':'执行者','ACTOR':'执行者','Action':'操作','ACTION':'操作','Target':'对象','TARGET':'对象',
  'View details':'查看详情','No activity logs found.':'未找到活动日志。','System / Guest':'系统 / 访客',
  'Log details':'日志详情','Before':'变更前','After':'变更后','No data':'无数据','Close':'关闭',
  'Post created':'已创建文章','Post updated':'已更新文章','Post submitted':'文章已提交审核','Post deleted':'已删除文章',
  'Category translated':'已翻译分类','User created':'已创建用户','User locked':'已锁定用户','User unlocked':'已解锁用户',
  'Role changed':'已更改角色','Language updated':'已更新语言','Language deleted':'已删除语言',
  'Settings updated':'已更新设置','Settings restored':'已恢复设置','Login failed':'登录失败','Access denied':'访问被拒绝',

  'About':'关于','Change cover':'更换封面','Personal information':'个人信息',
  'Date of birth':'出生日期','Member':'成员','Verification':'验证',
  'Verified':'已验证','Not verified':'未验证',

  'Search by name or email...':'按姓名或邮箱搜索...',
  'Cancel':'取消','Confirm':'确认','Delete':'删除','Edit':'编辑','Save changes':'保存更改',
  'Previous':'上一页','Next':'下一页','Page':'页','Total':'总计','Go':'跳转',
  'Items/page':'每页数量','Go to page':'前往页码','Apply':'应用','Logout':'退出登录',
  'Are you sure you want to log out of this account?':'确定要退出此账户吗？',
  'of':'共',
};

export const ZH_KEYS: Record<string, string> = {
  'nav.home':'首页','nav.profile':'个人资料','nav.dashboard':'控制面板',
  'nav.managePosts':'管理文章','nav.manageUsers':'管理用户',
  'nav.manageCategories':'管理分类','nav.manageLanguages':'管理语言',
  'nav.backToBlog':'返回博客','action.search':'搜索...',
  'action.signIn':'登录','action.getStarted':'开始使用',
  'action.logout':'退出登录','action.cancel':'取消','action.confirm':'确认',
  'activityLogs':'活动日志',
};
