import { ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, HostListener, inject, signal, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { LanguageService } from '../../core/services/language.service';
import { MockDatabaseService } from '../../data/mock/mock-database.service';

interface ArticleView { id:number; authorId:number; categoryId:number; title:string; content:string; thumbnail:string; category:string; author:string; avatar:string|null; date:string; likes:number; comments:number; }
interface CommentView { id:number; name:string; initial:string; content:string; date:string; depth:number; }

@Component({selector:'app-article',standalone:true,imports:[RouterLink],templateUrl:'./article.component.html',styleUrl:'./article.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,encapsulation:ViewEncapsulation.None,schemas:[CUSTOM_ELEMENTS_SCHEMA]})
export class ArticleComponent {
  private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly database=inject(MockDatabaseService);protected readonly auth=inject(AuthService);protected readonly language=inject(LanguageService);private readonly revision=signal(0);
  protected readonly commentText=signal('');protected readonly replyTo=signal<number|null>(null);protected readonly replyText=signal('');protected readonly id=Number(this.route.snapshot.paramMap.get('id'));private readonly preview=this.route.snapshot.queryParamMap.get('preview')==='1';
  protected readonly article=computed<ArticleView|null>(()=>{this.revision();const post=this.database.table('posts').find(p=>p.id===this.id&&!p.deleted_at);if(!post)return null;const user=this.auth.currentUser();const mayPreview=this.preview&&!!user&&(user.id===post.author_id||user.role.nameRole==='SUPER_ADMIN');if(post.status!=='PUBLISHED'&&!mayPreview)return null;const languageId=this.language.contentLanguageId();const translations=this.database.table('post_translations');const translation=translations.find(t=>t.post_id===post.id&&t.language_id===languageId)??translations.find(t=>t.post_id===post.id);const author=this.database.table('users').find(u=>u.id===post.author_id);const categoryTranslations=this.database.table('category_translation');return{id:post.id,authorId:post.author_id,categoryId:post.category_id,title:translation?.title??'',content:translation?.content??'',thumbnail:post.thumbnail,category:categoryTranslations.find(t=>t.category_id===post.category_id&&t.language_id===languageId)?.name??categoryTranslations.find(t=>t.category_id===post.category_id)?.name??'',author:author?.full_name||author?.user_name||'Anonymous',avatar:author?.avatar??null,date:post.published_at??post.created_at,likes:this.database.table('post_likes').filter(x=>x.post_id===post.id&&x.is_liked).length,comments:this.database.table('comments').filter(x=>x.post_id===post.id&&!x.deleted_at).length};});
  protected readonly liked=computed(()=>{this.revision();const uid=this.auth.currentUser()?.id;return !!uid&&this.database.table('post_likes').some(x=>x.post_id===this.id&&x.user_id===uid&&x.is_liked);});
  protected readonly bookmarked=computed(()=>{this.revision();const uid=this.auth.currentUser()?.id;return !!uid&&this.database.table('post_bookmarks').some(x=>x.post_id===this.id&&x.user_id===uid);});
  protected readonly related=computed(()=>{this.revision();const current=this.article();if(!current)return[];const languageId=this.language.contentLanguageId();const translations=this.database.table('post_translations');const categories=this.database.table('category_translation');const users=this.database.table('users');return this.database.table('posts').filter(p=>p.status==='PUBLISHED'&&!p.deleted_at&&p.id!==current.id).sort((a,b)=>Number(b.category_id===current.categoryId)-Number(a.category_id===current.categoryId)).slice(0,3).map(p=>({id:p.id,title:translations.find(t=>t.post_id===p.id&&t.language_id===languageId)?.title??translations.find(t=>t.post_id===p.id)?.title??'',thumbnail:p.thumbnail,category:categories.find(t=>t.category_id===p.category_id&&t.language_id===languageId)?.name??'',author:users.find(u=>u.id===p.author_id)?.full_name??'',date:p.published_at??p.created_at}));});
  protected readonly comments=computed<CommentView[]>(()=>{this.revision();const rows=this.database.table('comments').filter(c=>c.post_id===this.id&&!c.deleted_at);const users=this.database.table('users');const output:CommentView[]=[];const append=(parentId:number|null,depth:number)=>rows.filter(c=>c.parent_id===parentId).forEach(c=>{const user=users.find(u=>u.id===c.user_id);const name=user?.full_name||user?.user_name||'Anonymous';output.push({id:c.id,name,initial:name.charAt(0).toUpperCase(),content:c.content,date:c.created_at,depth});append(c.id,depth+1);});append(null,0);return output;});
  protected formatDate(value:string):string{return new Intl.DateTimeFormat(this.language.formatLocale(),{month:'short',day:'numeric',year:'numeric'}).format(new Date(value));}
  protected toggleLike():void{const user=this.auth.currentUser();if(!user)return;const rows=this.database.table('post_likes');const found=rows.find(x=>x.post_id===this.id&&x.user_id===user.id);if(found){found.is_liked=!found.is_liked;found.updated_at=new Date().toISOString();}else rows.push({id:this.database.nextId('post_likes'),post_id:this.id,user_id:user.id,is_liked:true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});this.database.write('post_likes',rows);this.revision.update(x=>x+1);}
  protected toggleBookmark():void{const user=this.auth.currentUser();if(!user)return;const rows=this.database.table('post_bookmarks');const index=rows.findIndex(x=>x.post_id===this.id&&x.user_id===user.id);if(index>=0)rows.splice(index,1);else rows.push({id:this.database.nextId('post_bookmarks'),post_id:this.id,user_id:user.id,created_at:new Date().toISOString()});this.database.write('post_bookmarks',rows);this.revision.update(x=>x+1);}
  protected submitComment(parentId:number|null):void{const user=this.auth.currentUser();if(!user)return;const value=(parentId===null?this.commentText():this.replyText()).trim();if(!value)return;const rows=this.database.table('comments');rows.push({id:this.database.nextId('comments'),post_id:this.id,user_id:user.id,parent_id:parentId,content:value,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),deleted_at:null});this.database.write('comments',rows);this.commentText.set('');this.replyText.set('');this.replyTo.set(null);this.revision.update(x=>x+1);}
  protected keySubmit(event:KeyboardEvent,parentId:number|null):void{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();this.submitComment(parentId);}}
  protected focusComment():void{document.querySelector<HTMLElement>('.responses-section')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.querySelector<HTMLTextAreaElement>('.comment-input .comment-textarea')?.focus());}
  @HostListener('click',['$event']) protected openAuthor(event:MouseEvent):void{const target=(event.target as HTMLElement).closest('.byline .author-name,.byline .author-avatar');if(!target)return;event.preventDefault();const id=this.article()?.authorId;if(id)void this.router.navigate(['/profile',id]);}
}
