import { ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, inject, signal, ViewEncapsulation } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { LanguageService } from '../../core/services/language.service';
import { MockDatabaseService } from '../../data/mock/mock-database.service';
import { PostRow, PostStatus } from '../../data/mock/mock-schema.model';
import { buildPaginationItems } from '../../shared/utils/pagination';

interface AdminPost {id:number;title:string;content:string;thumbnail:string;author:string;category:string;status:PostStatus;date:string;rejectionReason:string|null;}

@Component({selector:'app-admin-posts',standalone:true,imports:[RouterLink],templateUrl:'./admin-posts.component.html',styleUrl:'./admin-posts.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,encapsulation:ViewEncapsulation.None,schemas:[CUSTOM_ELEMENTS_SCHEMA]})
export class AdminPostsComponent {
  private readonly database=inject(MockDatabaseService);protected readonly auth=inject(AuthService);protected readonly language=inject(LanguageService);private readonly revision=signal(0);
  protected readonly search=signal('');protected readonly status=signal('');protected readonly sort=signal('newest');protected readonly page=signal(1);protected readonly pageSize=signal(5);protected readonly pageInput=signal(1);protected readonly sizeInput=signal(5);protected readonly previewId=signal<number|null>(null);protected readonly approveId=signal<number|null>(null);protected readonly rejectId=signal<number|null>(null);protected readonly rejectionReason=signal('');protected readonly error=signal('');
  protected readonly posts=computed<AdminPost[]>(()=>{this.revision();const langId=this.language.languageId();const translations=this.database.table('post_translations');const categories=this.database.table('category_translation');const users=this.database.table('users');return this.database.table('posts').filter(p=>!p.deleted_at).map(p=>{const translation=translations.find(t=>t.post_id===p.id&&t.language_id===langId)??translations.find(t=>t.post_id===p.id);return{id:p.id,title:translation?.title??'Untitled',content:translation?.content??'',thumbnail:p.thumbnail,author:users.find(u=>u.id===p.author_id)?.full_name??'Unknown',category:categories.find(c=>c.category_id===p.category_id&&c.language_id===langId)?.name??categories.find(c=>c.category_id===p.category_id)?.name??'Unknown',status:p.status,date:p.created_at,rejectionReason:p.rejection_reason};});});
  protected readonly stats=computed(()=>{const rows=this.posts();return[{vi:'Tổng số bài',en:'Total Posts',value:rows.length,color:''},{vi:'Chờ duyệt',en:'Pending',value:rows.filter(p=>p.status==='PENDING').length,color:'var(--icon-star)'},{vi:'Đã duyệt',en:'Approved',value:rows.filter(p=>p.status==='PUBLISHED').length,color:'var(--accent)'},{vi:'Bị từ chối',en:'Rejected',value:rows.filter(p=>p.status==='REJECTED').length,color:'var(--danger)'}];});
  protected readonly filtered=computed(()=>{const q=this.search().trim().toLocaleLowerCase();return this.posts().filter(p=>(!q||p.title.toLocaleLowerCase().includes(q)||p.author.toLocaleLowerCase().includes(q))&&(!this.status()||p.status===this.status())).sort((a,b)=>this.sort()==='oldest'?+new Date(a.date)-+new Date(b.date):this.sort()==='title-asc'?a.title.localeCompare(b.title):this.sort()==='title-desc'?b.title.localeCompare(a.title):+new Date(b.date)-+new Date(a.date));});
  protected readonly totalPages=computed(()=>Math.max(1,Math.ceil(this.filtered().length/this.pageSize())));protected readonly pages=computed(()=>buildPaginationItems(this.page(),this.totalPages()));protected readonly visible=computed(()=>this.filtered().slice((this.page()-1)*this.pageSize(),this.page()*this.pageSize()));protected readonly preview=computed(()=>this.posts().find(p=>p.id===this.previewId())??null);protected readonly summary=computed(()=>{const total=this.filtered().length;const from=total?(this.page()-1)*this.pageSize()+1:0;const to=Math.min(this.page()*this.pageSize(),total);return this.language.choose(`Hiển thị ${from}–${to} trong tổng số ${total}`,`Showing ${from}–${to} of ${total}`);});
  protected label(row:{vi:string;en:string}):string{return this.language.choose(row.vi,row.en);}protected formatDate(value:string):string{return new Intl.DateTimeFormat(this.language.formatLocale()).format(new Date(value));}protected setFilter(type:'search'|'status'|'sort',value:string):void{if(type==='search')this.search.set(value);if(type==='status')this.status.set(value);if(type==='sort')this.sort.set(value);this.page.set(1);}protected statusLabel(status:PostStatus):string{const vi={DRAFT:'Bản nháp',PENDING:'Chờ duyệt',PUBLISHED:'Đã duyệt',REJECTED:'Bị từ chối'};const en={DRAFT:'Draft',PENDING:'Pending',PUBLISHED:'Approved',REJECTED:'Rejected'};return this.language.chooseObject(vi,en)[status];}
  protected changePage(value:number):void{const next=Math.min(Math.max(1,value),this.totalPages());this.page.set(next);this.pageInput.set(next);document.querySelector('.filter-bar')?.scrollIntoView({behavior:'smooth',block:'start'});}protected applyPage():void{this.changePage(this.pageInput());}protected applyPageSize():void{const size=Math.min(100,Math.max(1,Math.trunc(this.sizeInput()||1)));this.pageSize.set(size);this.sizeInput.set(size);this.changePage(1);}
  protected confirmApprove():void{const id=this.approveId();if(id===null)return;this.changeStatus(id,'PUBLISHED',null,'POST_APPROVED');this.approveId.set(null);}
  protected submitReject():void{const reason=this.rejectionReason().trim();if(!reason){this.error.set(this.language.choose('Vui lòng nhập lý do từ chối!','Please enter a rejection reason.'));return;}const id=this.rejectId();if(id===null)return;this.changeStatus(id,'REJECTED',reason,'POST_REJECTED');this.rejectId.set(null);this.rejectionReason.set('');this.error.set('');}
  private changeStatus(id:number,status:'PUBLISHED'|'REJECTED',reason:string|null,action:string):void{const posts=this.database.table('posts');const post=posts.find(p=>p.id===id);if(!post||post.status!=='PENDING')return;const before=structuredClone(post);const now=new Date().toISOString();post.status=status;post.rejection_reason=reason;post.reviewed_by=this.auth.currentUser()?.id??null;post.reviewed_at=now;post.published_at=status==='PUBLISHED'?now:null;post.updated_at=now;this.database.write('posts',posts);this.recordLog(action,post,before);this.revision.update(x=>x+1);}
  private recordLog(action:string,post:PostRow,before:PostRow):void{const user=this.auth.currentUser();const logs=this.database.table('audit_logs');logs.push({id:this.database.nextId('audit_logs'),actor_id:user?.id??null,actor_name:user?.fullName??user?.userName??null,actor_role:user?.role.nameRole??null,action,entity_type:'POST',entity_id:post.id,entity_label:this.posts().find(p=>p.id===post.id)?.title??null,before_data:before,after_data:structuredClone(post),metadata:null,ip_address:null,user_agent:navigator.userAgent,created_at:new Date().toISOString()});this.database.write('audit_logs',logs);}
}
