import { ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, effect, inject, OnInit, signal, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ContentPost } from '../../core/models/content.model';
import { AdminContentApiService } from '../../core/services/admin-content-api.service';
import { AuthService } from '../../core/services/auth.service';
import { LanguageService } from '../../core/services/language.service';
import { buildPaginationItems } from '../../shared/utils/pagination';

type PostStatus=ContentPost['status'];
interface AdminPost {id:number;title:string;content:string;thumbnail:string;author:string;category:string;status:PostStatus;date:string;rejectionReason:string|null;}

@Component({selector:'app-admin-posts',standalone:true,imports:[RouterLink],templateUrl:'./admin-posts.component.html',styleUrl:'./admin-posts.component.scss',changeDetection:ChangeDetectionStrategy.OnPush,encapsulation:ViewEncapsulation.None,schemas:[CUSTOM_ELEMENTS_SCHEMA]})
export class AdminPostsComponent implements OnInit {
  private readonly api=inject(AdminContentApiService);protected readonly auth=inject(AuthService);protected readonly language=inject(LanguageService);private readonly route=inject(ActivatedRoute);
  private readonly rows=signal<ContentPost[]>([]);private readonly statusStats=signal({total:0,DRAFT:0,PENDING:0,PUBLISHED:0,REJECTED:0});private readonly total=signal(0);private readonly totalPageCount=signal(1);
  protected readonly search=signal('');protected readonly status=signal('');protected readonly sort=signal('newest');protected readonly page=signal(1);protected readonly pageSize=signal(5);protected readonly pageInput=signal(1);protected readonly sizeInput=signal(5);protected readonly previewId=signal<number|null>(null);protected readonly approveId=signal<number|null>(null);protected readonly unapproveId=signal<number|null>(null);protected readonly rejectId=signal<number|null>(null);protected readonly rejectionReason=signal('');protected readonly error=signal('');
  constructor(){effect(()=>{const page=this.page(),limit=this.pageSize(),search=this.search().trim(),status=this.status(),sort=this.sort();this.api.posts({page,limit,search,status,sort}).subscribe({next:r=>{this.rows.set(r.data.items);this.statusStats.set(r.data.stats);this.total.set(r.data.pagination.total);this.totalPageCount.set(Math.max(1,r.data.pagination.totalPages));},error:e=>{this.rows.set([]);this.error.set(e instanceof Error?e.message:'LOAD_POSTS_FAILED');}});},{allowSignalWrites:true});}
  ngOnInit():void{this.route.queryParams.subscribe(params=>{if(params['status'])this.status.set(params['status']);});}
  protected readonly posts=computed<AdminPost[]>(()=>this.rows().map(row=>this.map(row)));
  protected readonly stats=computed(()=>{const rows=this.statusStats();return[{vi:'Tổng số bài',en:'Total Posts',value:rows.total,color:''},{vi:'Chờ duyệt',en:'Pending',value:rows.PENDING,color:'var(--icon-star)'},{vi:'Đã duyệt',en:'Approved',value:rows.PUBLISHED,color:'var(--accent)'},{vi:'Bị từ chối',en:'Rejected',value:rows.REJECTED,color:'var(--danger)'}];});
  protected readonly filtered=computed(()=>this.posts());protected readonly totalPages=computed(()=>this.totalPageCount());protected readonly pages=computed(()=>buildPaginationItems(this.page(),this.totalPages()));protected readonly visible=computed(()=>this.posts());protected readonly preview=computed(()=>this.posts().find(p=>p.id===this.previewId())??null);protected readonly summary=computed(()=>{const total=this.total();const from=total?(this.page()-1)*this.pageSize()+1:0;const to=Math.min(this.page()*this.pageSize(),total);return this.language.translate('pagination.summary',{from,to,total});});
  protected label(row:{vi:string;en:string}):string{return this.language.choose(row.vi,row.en);}protected formatDate(value:string):string{return new Intl.DateTimeFormat(this.language.formatLocale()).format(new Date(value));}protected setFilter(type:'search'|'status'|'sort',value:string):void{if(type==='search')this.search.set(value);if(type==='status')this.status.set(value);if(type==='sort')this.sort.set(value);this.page.set(1);}protected statusLabel(status:PostStatus):string{const vi={DRAFT:'Bản nháp',PENDING:'Chờ duyệt',PUBLISHED:'Đã duyệt',REJECTED:'Bị từ chối'};const en={DRAFT:'Draft',PENDING:'Pending',PUBLISHED:'Approved',REJECTED:'Rejected'};return this.language.chooseObject(vi,en)[status];}
  protected changePage(value:number):void{const next=Math.min(Math.max(1,value),this.totalPages());this.page.set(next);this.pageInput.set(next);document.querySelector('.filter-bar')?.scrollIntoView({behavior:'smooth',block:'start'});}protected applyPage():void{this.changePage(this.pageInput());}protected applyPageSize():void{const size=Math.min(100,Math.max(1,Math.trunc(this.sizeInput()||1)));this.pageSize.set(size);this.sizeInput.set(size);this.changePage(1);}
  protected confirmApprove():void{const id=this.approveId();if(id===null)return;this.api.approve(String(id)).subscribe({next:()=>{this.approveId.set(null);this.reload();},error:e=>this.error.set(e instanceof Error?e.message:'POST_APPROVE_FAILED')});}
  protected confirmUnapprove():void{const id=this.unapproveId();if(id===null)return;this.api.unapprove(String(id)).subscribe({next:()=>{this.unapproveId.set(null);this.reload();},error:e=>this.error.set(e instanceof Error?e.message:'POST_UNAPPROVE_FAILED')});}
  protected submitReject():void{const reason=this.rejectionReason().trim();if(!reason){this.error.set(this.language.choose('Vui lòng nhập lý do từ chối!','Please enter a rejection reason.'));return;}const id=this.rejectId();if(id===null)return;this.api.reject(String(id),reason).subscribe({next:()=>{this.rejectId.set(null);this.rejectionReason.set('');this.error.set('');this.reload();},error:e=>this.error.set(e instanceof Error?e.message:'POST_REJECT_FAILED')});}
  private reload():void{this.api.posts({page:this.page(),limit:this.pageSize(),search:this.search().trim(),status:this.status(),sort:this.sort()}).subscribe(r=>{this.rows.set(r.data.items);this.statusStats.set(r.data.stats);this.total.set(r.data.pagination.total);this.totalPageCount.set(Math.max(1,r.data.pagination.totalPages));});}
  private map(row:ContentPost):AdminPost{const languageId=this.language.languageId();const translation=row.translations.find(item=>item.languageId===languageId)??row.translations[0];const category=row.category?.translations.find(item=>item.languageId===languageId)??row.category?.translations[0];return{id:Number(row.id),title:translation?.title??'Untitled',content:translation?.content??'',thumbnail:row.thumbnail,author:row.author?.fullName||row.author?.userName||'Unknown',category:category?.name??'Unknown',status:row.status,date:row.createdAt,rejectionReason:(row as ContentPost&{rejectionReason?:string|null}).rejectionReason??null};}
}
